import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createApp} from '../server/app.js';import {Store} from '../server/storage.js';import type {ConnectorService} from '../server/queue.js';import type {Bootstrap,Content,Variant,Connection,Job} from '../server/types.js';
test('local API end-to-end: profiles, variants, approval, encrypted channels, durable idempotent per-target publishing',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'creator-api-'));const store=new Store(dir);let posts=0;
 const service:ConnectorService={getConnectorDefinitions:ps=>ps.map(p=>({id:`native:${p.id}`,name:'Mock only',description:'Never real network',platformIds:[p.id],fields:[{key:'token',label:'Token',secret:true,required:true}],mode:p.id==='wechat'?'draft':'publish'})),validateConnection:c=>c.config.token?[]:['Token missing'],testConnection:async()=>({ok:true,message:'Mock connection verified'}),publish:async(c)=>{posts++;return {status:c.platformId==='wechat'?'drafted':'published',message:'Mock terminal receipt',remoteId:`mock-${posts}`};}};
 const instance=createApp({store,connectors:service,startQueue:false});const server=instance.app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const port=(server.address() as {port:number}).port;const base=`http://127.0.0.1:${port}`;
 async function api(path:string,method='GET',body?:unknown,headers:Record<string,string>={}){const res=await fetch(`${base}/api${path}`,{method,headers:{'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});return {status:res.status,body:await res.json() as any};}
 try {
  assert.equal((await api('/health')).body.ok,true);
  const denied=await api('/contents','POST',{title:'x',source:'x'},{Origin:'https://attacker.example'});assert.equal(denied.status,403);
  const profile=(await api('/profiles','POST',{name:'我的账号',audience:'创作者',tone:'清楚',description:'经验分享',language:'中文',forbiddenWords:['禁用']})).body;
  const c:Content=(await api('/contents','POST',{title:'长期创作',source:'把亲身经验整理成结构化内容，保留原始事实。',profileId:profile.id,media:[]})).body;
  const generated=await api(`/contents/${c.id}/generate`,'POST',{platformIds:['reddit','wechat','x'],mode:'rules'});assert.equal(generated.status,200);const variants:Variant[]=generated.body.variants;assert.equal(variants.length,3);
  for(const v of variants)assert.equal((await api(`/variants/${v.id}`,'PUT',{approved:true})).body.approved,true);
  const connections:Connection[]=[];for(const platformId of ['reddit','wechat']){const result=await api('/connections','POST',{name:platformId,platformId,connector:'native',config:{token:'my-secret-token'}});assert.equal(result.status,201);assert.ok(!JSON.stringify(result.body).includes('my-secret-token'));assert.deepEqual(result.body.secretKeys,['token']);connections.push(result.body);}
  const edited=await api(`/connections/${connections[0].id}`,'PUT',{name:'Reddit account',platformId:'reddit',connector:'native',config:{token:''}});assert.equal(edited.body.configured,true);assert.equal((await api(`/connections/${connections[0].id}/test`,'POST',{})).body.ok,true);
  const targets=connections.map(connection=>({connectionId:connection.id,variantId:variants.find(v=>v.platformId===connection.platformId)!.id}));const request={contentId:c.id,targets};
  const created=await api('/jobs','POST',request,{'Idempotency-Key':'test-request-1'});assert.equal(created.status,201);const replay=await api('/jobs','POST',request,{'Idempotency-Key':'test-request-1'});assert.equal(replay.status,200);assert.deepEqual(replay.body.jobs.map((j:Job)=>j.id),created.body.jobs.map((j:Job)=>j.id));
  await instance.queue.tick();const bootstrap:Bootstrap=(await api('/bootstrap')).body;assert.equal(bootstrap.jobs.length,2);assert.deepEqual(new Set(bootstrap.jobs.map(j=>j.status)),new Set(['published','drafted']));assert.equal(posts,2);assert.ok(!JSON.stringify(bootstrap).includes('my-secret-token'));
  const conflicting=await api('/jobs','POST',{contentId:c.id,targets:targets.slice(0,1)},{'Idempotency-Key':'test-request-1'});assert.equal(conflicting.status,409);
  const exported=await fetch(`${base}/api/contents/${c.id}/export?platformId=wechat&format=html`);assert.equal(exported.status,200);assert.match(await exported.text(),/style=/);
  const rawBlob=new Blob([new Uint8Array([137,80,78,71,13,10,26,10])],{type:'image/png'});const form=new FormData();form.set('file',rawBlob,'preview.png');const uploaded=await fetch(`${base}/api/uploads`,{method:'POST',body:form});assert.equal(uploaded.status,201);assert.equal((await uploaded.json() as any).mime,'image/png');
  const mutation=await api(`/variants/${variants[2].id}`,'PUT',{body:'编辑后的内容',approved:true});assert.equal(mutation.body.approved,false);assert.equal(mutation.body.source,'manual');
  await api(`/variants/${variants[2].id}`,'PUT',{approved:true});await api(`/contents/${c.id}`,'PUT',{title:c.title,source:'原稿已经修改',profileId:profile.id,media:[]});const stale=await api(`/variants/${variants[2].id}`,'PUT',{approved:true});assert.equal(stale.status,400);assert.match(stale.body.error,/校验错误/);
  assert.equal((await api('/settings','PUT',{generation:{enabled:true,baseUrl:'https://llm.invalid/v1',model:'model',apiKey:'generation-private-key'}})).body.generation.hasApiKey,true);assert.ok(!JSON.stringify((await api('/bootstrap')).body).includes('generation-private-key'));
  assert.equal((await api('/settings','PUT',{generation:{apiKey:''}})).body.generation.hasApiKey,true);assert.equal((await api('/settings','PUT',{generation:{clearApiKey:true}})).body.generation.hasApiKey,false);
 }finally{instance.queue.stop();await new Promise<void>(r=>server.close(()=>r()));store.close();rmSync(dir,{recursive:true,force:true});}
});
