import test from 'node:test';import assert from 'node:assert/strict';import {generateAI} from '../server/generation.js';import {platformById} from '../server/catalog.js';import {stamp,uid} from '../server/domain.js';
import {platforms} from '../server/catalog.js';
const c={id:uid(),title:'原创主题',source:'我写的原始内容',media:[],createdAt:stamp(),updatedAt:stamp()};
const config={enabled:true,baseUrl:'https://llm.invalid/v1',model:'test-model',apiKey:'private-llm-key'};
test('AI sends source and persona but never includes API credentials in prompt',async()=>{const original=globalThis.fetch;let request:any;globalThis.fetch=async(_url,init)=>{request=JSON.parse(String(init?.body));return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({variants:[{platformId:'zhihu',title:'文章',body:'保留原稿实质',tags:[],thread:[]}]})}}]}),{status:200,headers:{'Content-Type':'application/json'}});};try{const variants=await generateAI(c,[platformById('zhihu')],undefined,config);assert.equal(variants[0].source,'ai');assert.equal(variants[0].approved,false);assert.match(request.messages[1].content,/原始内容/);assert.ok(!JSON.stringify(request.messages).includes(config.apiKey));assert.ok(variants[0].html?.includes('保留原稿实质'));}finally{globalThis.fetch=original;}});
test('incomplete JSON or provider failures surface errors, never fabricated fallback',async()=>{const original=globalThis.fetch;try{globalThis.fetch=async()=>new Response(JSON.stringify({choices:[{message:{content:'{"variants":['}}]}),{status:200});await assert.rejects(()=>generateAI(c,[platformById('x')],undefined,config),/JSON/);globalThis.fetch=async()=>new Response('invalid key',{status:401});await assert.rejects(()=>generateAI(c,[platformById('x')],undefined,config),/HTTP 401/);await assert.rejects(()=>generateAI(c,[platformById('x')],undefined,{...config,enabled:false}),/启用 AI/);}finally{globalThis.fetch=original;}});
test('generation timeout also covers a stalled response body after headers', {timeout:1000}, async t=>{
 const original=globalThis.fetch;t.mock.timers.enable({apis:['setTimeout']});
 globalThis.fetch=async(_url,init)=>({ok:true,json:()=>new Promise((_resolve,reject)=>init?.signal?.addEventListener('abort',()=>reject(new Error('aborted body'))))} as Response);
 try{const pending=assert.rejects(generateAI(c,[platformById('x')],undefined,config),/90 秒/);await Promise.resolve();t.mock.timers.tick(90001);await pending;}finally{globalThis.fetch=original;t.mock.timers.reset();}
});
test('large platform selections use bounded structured batches and never return a partial result',async()=>{
 const original=globalThis.fetch;const sizes:number[]=[];let fail=false;
 globalThis.fetch=async(_url,init)=>{const request=JSON.parse(String(init?.body));const input=JSON.parse(request.messages[1].content);sizes.push(input.platforms.length);if(fail&&sizes.length===2)return new Response('rejected',{status:503});return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({variants:input.platforms.map((p:any)=>({platformId:p.id,title:'A title',body:'Original substantive text',tags:[],thread:[]}))})}}]}),{status:200});};
 try{const variants=await generateAI(c,platforms.slice(0,14),undefined,config);assert.equal(variants.length,14);assert.deepEqual(sizes,[6,6,2]);assert.equal(new Set(variants.map(v=>v.platformId)).size,14);sizes.length=0;fail=true;await assert.rejects(generateAI(c,platforms.slice(0,14),undefined,config),/HTTP 503/);assert.deepEqual(sizes,[6,6]);}finally{globalThis.fetch=original;}
});
