import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {Store} from '../server/storage.js';import {JobQueue,type ConnectorService} from '../server/queue.js';import {platforms,platformById} from '../server/catalog.js';import {ruleVariant,uid,stamp} from '../server/domain.js';import type {Job,ConnectionPrivate} from '../server/types.js';
const connection:ConnectionPrivate={id:'conn',name:'本地测试',platformId:'reddit',connector:'native',enabled:true,config:{token:'must-not-leak'}};
function fixture(service:ConnectorService){const dir=mkdtempSync(join(tmpdir(),'creator-queue-'));const store=new Store(dir);const c={id:uid(),title:'测试',source:'正文',media:[],createdAt:stamp(),updatedAt:stamp()};const snapshot={...ruleVariant(c,platformById('reddit')),approved:true};const job:Job={id:uid(),batchId:uid(),contentId:c.id,variantId:snapshot.id,connectionId:'conn',platformId:'reddit',connectionName:'本地测试',title:'测试',status:'queued',scheduledAt:stamp(),attempts:0,message:'等待',createdAt:stamp(),updatedAt:stamp(),snapshot,media:[]};store.put('job',job);return {store,job,queue:new JobQueue(store,platforms,service,()=>connection,'http://localhost:4318'),close(){store.close();rmSync(dir,{recursive:true,force:true});}};}
const service=(publish:ConnectorService['publish']):ConnectorService=>({getConnectorDefinitions:()=>[],validateConnection:()=>[],testConnection:async()=>({ok:true,message:'mock'}),publish});
test('scheduled targets do not run early and successful draft stays drafted',async()=>{let calls=0;const f=fixture(service(async()=>{calls++;return {status:'drafted',message:'draft created',remoteId:'draft-1'};}));try{f.store.put('job',{...f.job,status:'scheduled',scheduledAt:new Date(Date.now()+60000).toISOString()});await f.queue.tick();assert.equal(calls,0);f.store.put('job',{...f.job,scheduledAt:new Date(Date.now()-1000).toISOString()});await f.queue.tick();assert.equal(calls,1);assert.equal(f.store.get<Job>('job',f.job.id)?.status,'drafted');await f.queue.tick();assert.equal(calls,1);}finally{f.close();}});
test('concurrent ticks claim once, unknown mutation outcomes are never blindly retried',async()=>{let calls=0;const f=fixture(service(async()=>{calls++;await new Promise(r=>setTimeout(r,10));throw Object.assign(new Error('timeout token must-not-leak'),{uncertain:true});}));try{await Promise.all([f.queue.tick(),f.queue.tick()]);await f.queue.tick();const job=f.store.get<Job>('job',f.job.id)!;assert.equal(calls,1);assert.equal(job.status,'unconfirmed');assert.ok(!job.message.includes('must-not-leak'));assert.equal(job.attempts,1);}finally{f.close();}});
test('crash recovery records uncertainty rather than reposting',async()=>{let calls=0;const f=fixture(service(async()=>{calls++;return {status:'published',message:'mock'};}));try{f.store.put('job',{...f.job,status:'running'});f.queue.recover();await f.queue.tick();assert.equal(calls,0);assert.equal(f.store.get<Job>('job',f.job.id)?.status,'unconfirmed');}finally{f.close();}});
test('Postiz reconciliation uses read-only proof and never sends a second publish',async()=>{let checks=0;let posts=0;const s=service(async()=>{posts++;return {status:'unconfirmed',message:'remote accepted',remoteId:'remote-1'};});s.checkPublication=async()=>{checks++;return {status:'published',message:'remote status verified',url:'https://example.com/p/1'};};const f=fixture(s);try{(connection as any).connector='postiz';await f.queue.tick();await f.queue.tick();assert.equal(posts,1);assert.equal(checks,1);assert.equal(f.store.get<Job>('job',f.job.id)?.status,'published');}finally{connection.connector='native';f.close();}});
test('definite remote failure ends reconciliation without reposting',async()=>{let posts=0;const s=service(async()=>{posts++;return {status:'unconfirmed',message:'accepted',remoteId:'remote-1'};});s.checkPublication=async()=>{throw Object.assign(new Error('remote failure must-not-leak'),{terminalFailure:true});};const f=fixture(s);try{connection.connector='postiz';await f.queue.tick();await f.queue.tick();assert.equal(posts,1);const job=f.store.get<Job>('job',f.job.id)!;assert.equal(job.status,'failed');assert.ok(!job.message.includes('must-not-leak'));}finally{connection.connector='native';f.close();}});
