import type {Platform} from './types.js';

type Entry = [string,string,string,'domestic'|'global','article'|'social'|'video',number,number,string,string?,string?,string?];
const entries:Entry[] = [
 ['x','X / Twitter','X','global','social',0,280,'简洁观点与连续串帖','x','DYNAMIC_X'],
 ['reddit','Reddit','R','global','social',300,10000,'社区语境、实质信息与开放讨论','reddit','DYNAMIC_REDDIT'],
 ['xiaohongshu','小红书','小红书','domestic','social',20,1000,'真实体验、短段落和实用清单',undefined,'DYNAMIC_REDNOTE'],
 ['zhihu','知乎','知乎','domestic','article',100,20000,'论点、解释、证据与推理',undefined,'ARTICLE_ZHIHU','zhihu'],
 ['wechat','微信公众号','公众号','domestic','article',64,20000,'清晰叙事、层次结构与阅读节奏',undefined,'ARTICLE_WEIXIN','weixin'],
 ['linkedin','LinkedIn','in','global','social',0,3000,'专业经验与可操作的行业洞察','linkedin','DYNAMIC_LINKEDIN'],
 ['threads','Threads','Threads','global','social',0,500,'自然口语和轻量交流','threads','DYNAMIC_THREADS'],
 ['bluesky','Bluesky','Bluesky','global','social',0,300,'简洁表达和社区交流','bluesky','DYNAMIC_BLUESKY'],
 ['mastodon','Mastodon','M','global','social',0,500,'社区友好的观点与上下文','mastodon'],
 ['facebook','Facebook','f','global','social',0,63206,'易读故事、背景与互动','facebook','DYNAMIC_FACEBOOK'],
 ['instagram','Instagram','IG','global','social',0,2200,'视觉叙事与简洁说明','instagram','DYNAMIC_INSTAGRAM'],
 ['tiktok','TikTok','TikTok','global','video',0,2200,'前几秒抓住注意、短视频脚本','tiktok','VIDEO_TIKTOK'],
 ['youtube','YouTube','YT','global','video',100,5000,'视频标题、摘要与章节说明','youtube','VIDEO_YOUTUBE'],
 ['pinterest','Pinterest','Pin','global','social',100,500,'视觉灵感、具体关键词与用途','pinterest','DYNAMIC_PINTEREST'],
 ['bilibili','哔哩哔哩','B站','domestic','video',80,2000,'内容导读、视频结构与兴趣社区',undefined,'VIDEO_BILIBILI'],
 ['douyin','抖音','抖音','domestic','video',55,1000,'短视频开场、口播与结尾互动',undefined,'VIDEO_DOUYIN'],
 ['kuaishou','快手','快手','domestic','video',50,1000,'真实场景、直接表达与口播',undefined,'VIDEO_KUAISHOU'],
 ['wechat_channels','微信视频号','视频号','domestic','video',50,1000,'熟人传播、口播脚本与摘要',undefined,'VIDEO_WEIXINCHANNEL'],
 ['weibo','微博','微博','domestic','social',0,2000,'及时观点、重点信息与话题',undefined,'DYNAMIC_WEIBO','weibo'],
 ['toutiao','今日头条','头条','domestic','article',30,20000,'清晰标题、事实脉络与大众表达',undefined,'ARTICLE_TOUTIAO'],
 ['baijiahao','百家号','百家号','domestic','article',30,20000,'信息完整、段落清楚与关键词',undefined,'ARTICLE_BAIJIAHAO','baijiahao'],
 ['csdn','CSDN','CSDN','domestic','article',100,20000,'技术背景、步骤与可复现说明',undefined,'ARTICLE_CSDN','csdn'],
 ['juejin','掘金','掘金','domestic','article',100,20000,'技术过程、经验和代码解释',undefined,'ARTICLE_JUEJIN','juejin'],
 ['devto','DEV Community','DEV','global','article',150,20000,'技术教程与清晰的 Markdown','devto'],
 ['hashnode','Hashnode','Hashnode','global','article',150,20000,'开发实践与完整技术文章','hashnode'],
 ['wordpress','WordPress','WP','global','article',200,20000,'结构化长文与搜索友好表达','wordpress','ARTICLE_WORDPRESS'],
 ['medium','Medium','Medium','global','article',200,20000,'有叙事性的长文与清晰论述','medium','ARTICLE_MEDIUM'],
 ['telegram','Telegram','TG','global','social',0,4096,'频道更新与清晰的要点','telegram'],
 ['discord','Discord','Discord','global','social',0,2000,'社区消息与简洁更新','discord'],
 ['slack','Slack','Slack','global','social',0,4000,'团队公告与可执行要点','slack'],
 ['lemmy','Lemmy','Lemmy','global','social',200,10000,'社区讨论与充分背景','lemmy'],
 ['nostr','Nostr','Nostr','global','social',0,10000,'开放网络上的观点与交流','nostr'],
 ['vk','VK','VK','global','social',0,2048,'社区动态与短段落','vk'],
 ['tumblr','Tumblr','Tumblr','global','article',200,20000,'创作表达、图文与标签','tumblr'],
 ['jianshu','简书','简书','domestic','article',100,20000,'故事、经验与自然的长文叙事',undefined,'ARTICLE_JIANSHU'],
 ['cnblogs','博客园','博客园','domestic','article',100,20000,'技术背景、代码、步骤与复现结果',undefined,'ARTICLE_CNBLOGS','cnblogs'],
 ['segmentfault','SegmentFault 思否','思否','domestic','article',100,20000,'具体技术问题、解决方案与清晰代码',undefined,'ARTICLE_SEGMENTFAULT','segmentfault'],
 ['oschina','开源中国','OSChina','domestic','article',100,20000,'开源实践、工程经验与使用说明',undefined,'ARTICLE_OSCHINA','oschina'],
 ['sspai','少数派','少数派','domestic','article',100,20000,'亲身体验、使用过程与具体结论',undefined,'ARTICLE_SSPAI'],
 ['infoq','InfoQ','InfoQ','domestic','article',100,20000,'架构背景、技术权衡和工程价值',undefined,'ARTICLE_INFOQ'],
 ['aliyun','阿里云开发者社区','阿里云','domestic','article',100,20000,'技术教程、实践步骤和代码说明',undefined,'ARTICLE_ALIYUN'],
 ['tencent_cloud','腾讯云开发者社区','腾讯云','domestic','article',100,20000,'技术实践、部署过程与可复现案例',undefined,'ARTICLE_TENCENTYUN'],
 ['volcengine','火山引擎开发者社区','火山引擎','domestic','article',100,20000,'技术方案、实验过程与具体步骤',undefined,'ARTICLE_VOLCENGINE'],
 ['yuque','语雀','语雀','domestic','article',100,20000,'知识文档、结构化说明与协作阅读',undefined,undefined,'yuque'],
 ['cto51','51CTO','51CTO','domestic','article',100,20000,'技术教程、背景、步骤和注意事项',undefined,'ARTICLE_51CTO','51cto'],
 ['imooc','慕课手记','慕课','domestic','article',100,20000,'学习笔记、技术步骤和练习总结',undefined,undefined,'imooc'],
 ['woshipm','人人都是产品经理','产品经理','domestic','article',100,20000,'产品问题、用户场景、思路和案例',undefined,'ARTICLE_WOSHIPM','woshipm'],
 ['douban','豆瓣日记','豆瓣','domestic','article',100,20000,'个人观察、阅读体验和克制的表达',undefined,'ARTICLE_DOUBAN','douban'],
 ['xueqiu','雪球','雪球','domestic','article',100,20000,'事实与个人观点分开，明确证据和背景',undefined,'ARTICLE_XUEQIU','xueqiu'],
 ['eastmoney','东方财富','东财','domestic','article',100,20000,'信息来源、事实脉络与明确的观点',undefined,'ARTICLE_EASTMONEY','eastmoney'],
 ['sohu','搜狐号','搜狐','domestic','article',100,20000,'大众阅读、清晰标题与完整文章',undefined,'ARTICLE_SOHU','sohu'],
 ['netease','网易号','网易','domestic','article',100,20000,'易读标题、事实背景与有序叙事',undefined,'ARTICLE_NETEASE'],
 ['qie','企鹅号','企鹅','domestic','article',100,20000,'清楚标题、核心信息与短段落',undefined,'ARTICLE_QQ'],
 ['dayuhao','大鱼号','大鱼','domestic','article',100,20000,'大众兴趣、明确主题与简洁段落',undefined,'ARTICLE_DAYUHAO'],
 ['yidian','一点资讯','一点','domestic','article',100,20000,'清晰主题、事实脉络和易读表达',undefined,'ARTICLE_YIDIANZIXUN'],
 ['dingduanhao','顶端号','顶端','domestic','article',100,20000,'地域或行业背景、明确观点和完整叙事',undefined,'ARTICLE_DINGDUANHAO'],
 ['kuaichuanhao','快传号','快传','domestic','article',100,20000,'实质内容、可读标题与短段落',undefined,'ARTICLE_KUAICHUANHAO'],
 ['jianpian','简篇','简篇','domestic','article',100,20000,'图文叙事、自然段落和个人记录',undefined,'ARTICLE_JIANPIAN'],
 ['smzdm','什么值得买','值得买','domestic','article',100,20000,'实际使用、优缺点和有依据的体验',undefined,'ARTICLE_SMZDM'],
 ['autohome','汽车之家','汽车之家','domestic','article',100,20000,'具体使用场景、实际体验和明确结论',undefined,'ARTICLE_AUTOHOME'],
 ['dongchedi','懂车帝','懂车帝','domestic','article',100,20000,'真实体验、车型背景和具体细节',undefined,'ARTICLE_DONGCHEDI'],
 ['tonghuashun','同花顺','同花顺','domestic','article',100,20000,'信息来源、事实与个人判断分开',undefined,'ARTICLE_TONGHUASHUN'],
 ['zsxq','知识星球','星球','domestic','article',100,20000,'面向社群的深度分享、实践与讨论',undefined,'ARTICLE_ZSXQ'],
 ['jike','即刻','即刻','domestic','social',0,2000,'个人观察、自然语气与有趣的短表达',undefined,'DYNAMIC_OKJIKE'],
 ['v2ex','V2EX','V2EX','domestic','social',120,10000,'具体背景、实践细节和开放讨论',undefined,'DYNAMIC_V2EX'],
 ['dedao','得到','得到','domestic','social',0,2000,'知识笔记、核心观点与个人理解',undefined,'DYNAMIC_DEDAO'],
 ['xiaoheihe','小黑盒','小黑盒','domestic','social',100,2000,'游戏或兴趣体验、具体细节和社区表达',undefined,'DYNAMIC_XIAOHEIHE'],
 ['maimai','脉脉','脉脉','domestic','social',0,2000,'职场经验、具体场景与克制的表达',undefined,'DYNAMIC_MAIMAI'],
 ['gelonghui','格隆汇','格隆汇','domestic','article',100,20000,'信息依据、完整背景与明确观点',undefined,'ARTICLE_GELONGHUI'],
 ['jiankangjie','健康界','健康界','domestic','article',100,20000,'准确术语、信息来源与清晰论述',undefined,'ARTICLE_JIANKANGJIE'],
 ['kaidiwang','凯迪网','凯迪','domestic','article',100,20000,'完整背景、观点和理性讨论',undefined,'ARTICLE_KAIDIWANG'],
 ['alipay','支付宝生活号','生活号','domestic','video',100,1000,'生活场景、短视频开场与实用说明',undefined,'VIDEO_ALIPAY'],
 ['iqiyi','爱奇艺号','爱奇艺','domestic','video',100,2000,'视频标题、内容概要与观看理由',undefined,'VIDEO_IQIYI'],
 ['youku','优酷号','优酷','domestic','video',100,2000,'视频标题、核心内容与章节说明',undefined,'VIDEO_YOUKU'],
 ['tencent_video','腾讯视频','腾讯视频','domestic','video',100,2000,'视频标题、摘要和内容导读',undefined,'VIDEO_TENCENTVIDEO'],
 ['pinduoduo','拼多多视频','多多视频','domestic','video',100,1000,'短视频展示、实际场景与简洁说明',undefined,'VIDEO_PINDUODUO'],
 ['vivo_video','vivo 短视频','vivo','domestic','video',100,1000,'直接的短视频开场与内容摘要',undefined,'VIDEO_VIVOVIDEO'],
 ['dewu','得物','得物','domestic','video',100,1000,'真实体验、实物细节和兴趣表达',undefined,'VIDEO_DEWU'],
 ['yiche','易车','易车','domestic','video',100,2000,'车辆体验、实际场景与内容导读',undefined,'VIDEO_YICHE'],
 ['sohu_video','搜狐视频','搜狐视频','domestic','video',100,2000,'视频标题、摘要与观看重点',undefined,'VIDEO_SOHUTV'],
 ['google_business','Google Business Profile','Google 商家','global','social',0,1500,'商家近况、明确活动信息和行动指引','gmb'],
 ['dribbble','Dribbble','Dribbble','global','social',100,40000,'设计背景、创作过程与视觉说明','dribbble'],
 ['kick','Kick','Kick','global','social',0,500,'直播聊天与简洁频道公告','kick'],
 ['twitch','Twitch','Twitch','global','social',0,500,'直播聊天、频道公告和直接互动','twitch'],
 ['farcaster','Farcaster','Farcaster','global','social',0,800,'简洁观点、开放社区与互动','wrapcast'],
 ['listmonk','listmonk','listmonk','global','article',200,20000,'通讯标题、摘要与清晰的邮件长文','listmonk'],
 ['moltbook','Moltbook','Moltbook','global','social',100,300,'简洁观点与代理社区交流','moltbook'],
 ['whop','Whop','Whop','global','article',200,20000,'会员社区公告、经验分享与具体内容','whop'],
 ['skool','Skool','Skool','global','social',100,5000,'课程社群分享、步骤与讨论问题','skool'],
 ['mewe','MeWe','MeWe','global','social',0,63206,'个人近况、社群交流和易读表达','mewe'],
 ['ghost','Ghost','Ghost','global','article',200,20000,'独立出版、文章结构与通讯阅读'],
 ['misskey','Misskey','Misskey','global','social',0,3000,'社区交流、自然短帖与 MFM 表达'],
 ['blogger','Blogger','Blogger','global','article',200,20000,'博客长文、清晰结构与可读标题'],
 ['feishu','飞书群机器人','飞书','domestic','social',0,2000,'清晰公告、要点与行动事项'],
 ['dingtalk','钉钉群机器人','钉钉','domestic','social',0,2000,'团队通知、清晰要点和行动事项'],
 ['wecom','企业微信群机器人','企微','domestic','social',0,2000,'简洁群通知、重点与行动指引'],
 ['teams','Microsoft Teams','Teams','global','social',0,4000,'团队公告、结构化要点与后续行动'],
 ['substack','Substack','Substack','global','article',200,20000,'通讯叙事、个人观点与清晰的长文',undefined,'ARTICLE_SUBSTACK'],
 ['quora','Quora','Quora','global','article',200,10000,'直接回答问题、背景、论据与个人经验'],
 ['qiita','Qiita','Qiita','global','article',200,20000,'技术说明、代码与可复现步骤'],
 ['zenn','Zenn','Zenn','global','article',200,20000,'工程背景、清晰代码和技术经验'],
 ['note','note','note','global','article',200,20000,'个人写作、清晰段落与自然叙事'],
];
const experimental=new Set(['aliyun','tencent_cloud','volcengine','qie','gelonghui','jiankangjie','kaidiwang','jianpian','tonghuashun','dongchedi','zsxq','netease','sohu','dayuhao','dingduanhao','kuaichuanhao','yidian']);
const specificNotes:Record<string,string[]>={
 kick:['当前 Postiz 路径发布直播聊天消息，不上传直播或视频。'],twitch:['当前 Postiz 路径为聊天/频道公告，不创建直播视频。'],
 google_business:['需要 Postiz 中已授权的商家及地点，活动或按钮等字段需配置 settingsJson。'],
 listmonk:['用于自建通讯/邮件系统；收件列表、发布模式与实际发送由实例设置决定。'],
 moltbook:['面向 AI 代理社区，需要目标平台允许的代理账号与版块。'],
 hashnode:['原生发布/草稿接口要求符合 Hashnode 当前 API 权限与 publication 套餐。'],
 ghost:['Ghost 原生连接默认保存草稿；发表需显式选择 publish。'],
 blogger:['Blogger 原生连接默认保存草稿；需要具备目标博客写权限的 OAuth 令牌。'],
 lemmy:['原生连接需要实例、JWT 与社区 ID；只上传文字或嵌入可公开访问的图片。'],
 teams:['接入 Teams Workflows 的入站 Webhook；接收回执未必等于消息投递完成。'],
 feishu:['群机器人需要自己的 Webhook；可配置签名密钥，不读取个人会话。'],
 dingtalk:['群机器人需要自己的 Webhook；如启用签名/关键词策略，需要同时满足。'],
 wecom:['企业微信群机器人接入文字消息；受机器人消息配额限制。'],
 weibo:['MultiPost 对应微博动态；Wechatsync 对应微博长文章草稿，最终发布需在后台确认。'],
 substack:['公开参考扩展提供文章编辑页交接；通讯发送与最终发布仍在平台确认。'],
 quora:['当前提供内容适配、复制和导出；未实现专用发布连接。'],
 qiita:['当前提供内容适配、复制和导出；未实现专用发布连接。'],
 zenn:['当前提供内容适配、复制和导出；未实现 GitHub 仓库同步发布。'],
 note:['当前提供内容适配、复制和导出；未实现专用发布连接。'],
 xiaohongshu:['MCP REST 可选择图文或同机视频；视频服务必须直接运行在同一主机并能读取工作台文件路径，浏览器桥仅图文。'],
};
export const platforms:Platform[] = entries.map(([id,name,shortName,region,category,titleLimit,bodyLimit,recommendedTone,postizId,multipostId,wechatsyncId])=>({
 id,name,shortName,region,category,titleLimit,bodyLimit,recommendedTone,postizId,multipostId,wechatsyncId,
 color:region==='domestic'?'#176b52':'#52647a',
 description:`针对${name}优化结构、语气、标题和长度。`,
 formats:id==='xiaohongshu'?['dynamic','video']:category==='article'?['article']:category==='video'?['video']:['dynamic'],
 requiredMedia:['instagram','pinterest','dribbble'].includes(id)?'image':category==='video'&&id!=='tiktok'?'video':['tiktok','xiaohongshu'].includes(id)?'any':undefined,
 notes:[...(category==='video'?['生成的是视频文案与脚本，视频素材需要自行上传。']:[]),...(id==='wechat'?['公众号渠道可能只支持草稿；草稿成功与正式发布分开记录。']:[]),...(id==='reddit'?['发布时需要目标 subreddit，并遵循该社区规则。']:[]),...(id==='x'?['默认按普通账号的 280 加权字符拆分串帖。']:[]),...(multipostId?['浏览器路径依赖安装扩展、信任工作台与目标账号登录；回执只表示交接。']:[]),...(experimental.has(id)?['上游标记为实验性浏览器适配，页面填充与素材需逐渠道人工核验。']:[]),...(specificNotes[id]||[]),'内容长度为工作台默认值，实际发布权限与格式还受连接器和账号限制。']
}));
export function platformById(id:string):Platform {const platform=platforms.find(p=>p.id===id);if(!platform)throw new Error('未知平台');return platform;}
